# Generated by Django 5.0.4 on 2024-04-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='name',
            field=models.CharField(choices=[('VK', 'VK'), ('Telegram', 'Telegram'), ('YouTube', 'YouTube'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook')], max_length=100, verbose_name='Название'),
        ),
    ]
